Repository mattermost/mattermost-helm, pull requests merged in 2019-11, with the labels that each got.

#110 fix the mattermostApp externalPort variable
  charts/mattermost-enterprise-edition/Chart.yaml
  charts/mattermost-enterprise-edition/templates/NOTES.txt
Labels: 2: Reviews Complete

#121 Add loadbalancer settings to service.yaml
  charts/mattermost-team-edition/Chart.yaml
  charts/mattermost-team-edition/README.md
  charts/mattermost-team-edition/templates/service.yaml
  charts/mattermost-team-edition/values.yaml
Labels: 1: Dev Review, Lifecycle/1:stale

#123 Fix claimName of existing mattermost-plugins PVC
  charts/mattermost-team-edition/Chart.yaml
  charts/mattermost-team-edition/templates/deployment.yaml
Labels: 1: Dev Review
