Repository mattermost/mattermost-helm, pull requests merged in 2019-10, with the labels that each got.

#108 add PVC and volume mount for plugins directory
  charts/mattermost-team-edition/Chart.yaml
  charts/mattermost-team-edition/templates/deployment.yaml
  charts/mattermost-team-edition/templates/pvc-plugins.yaml
  charts/mattermost-team-edition/values.yaml
Labels: 1: Dev Review

#109 use configuration in the database
  charts/mattermost-enterprise-edition/Chart.yaml
  charts/mattermost-enterprise-edition/README.md
  charts/mattermost-enterprise-edition/templates/deployment-mattermost-app.yaml
  charts/mattermost-enterprise-edition/templates/deployment-mattermost-jobserver.yaml
  charts/mattermost-enterprise-edition/values.yaml
Labels: Lifecycle/frozen, Work In Progress

#116 Update mysql to version 1.4.0
  charts/mattermost-team-edition/Chart.yaml
  charts/mattermost-team-edition/requirements.lock
  charts/mattermost-team-edition/requirements.yaml
Labels: 2: Reviews Complete
