Repository mattermost/mattermost-helm, pull requests merged in 2020-02, with the labels that each got.

#132 MM-20705 Use correct apiVersion based on K8s version in mattermost-team-edition
  charts/mattermost-team-edition/Chart.yaml
  charts/mattermost-team-edition/templates/_helpers.tpl
  charts/mattermost-team-edition/templates/ingress.yaml
Labels: 1: Dev Review, Lifecycle/1:stale

#134 MM-20705 Use correct apiVersion based on K8s version in mattermost-enterprise-edition
  charts/mattermost-enterprise-edition/Chart.yaml
  charts/mattermost-enterprise-edition/templates/_helpers.tpl
  charts/mattermost-enterprise-edition/templates/ingress-mattermost-app.yaml
Labels: 2: Reviews Complete

#135 Add extraVolumes and Mounts
  charts/mattermost-team-edition/Chart.yaml
  charts/mattermost-team-edition/templates/deployment.yaml
  charts/mattermost-team-edition/values.yaml
Labels: 1: Dev Review
