Repository mattermost/mattermost-helm, pull requests merged in 2020-07, with the labels that each got.

#143 [mattermost-enterprise-edition] Allowing Annotation on MM Pods
  charts/mattermost-enterprise-edition/Chart.yaml
  charts/mattermost-enterprise-edition/templates/deployment-mattermost-app.yaml
  charts/mattermost-enterprise-edition/templates/deployment-mattermost-jobserver.yaml
  charts/mattermost-enterprise-edition/values.yaml
Labels: 1: Dev Review

#163 [GH-162] Added required ENV vars to use MinIO storage when enabled in values
  charts/mattermost-enterprise-edition/Chart.yaml
  charts/mattermost-enterprise-edition/templates/deployment-mattermost-app.yaml
Labels: 1: Dev Review

#172 update MM to 5.25.1
  charts/mattermost-team-edition/Chart.yaml
  charts/mattermost-team-edition/values.yaml
Labels: 2: Reviews Complete

#171 update MM to 5.25.1
  charts/mattermost-enterprise-edition/Chart.yaml
  charts/mattermost-enterprise-edition/values.yaml
Labels: 2: Reviews Complete

#165 Updated README.md to help users to deploy team-edition using helm v3.
  charts/mattermost-team-edition/Chart.yaml
  charts/mattermost-team-edition/README.md
Labels: 1: Dev Review

#175 bump MM to 5.25.2
  charts/mattermost-team-edition/Chart.yaml
  charts/mattermost-team-edition/values.yaml
Labels: AutoMerge

#176 update EE chart to use MM 5.25.2
  charts/mattermost-enterprise-edition/Chart.yaml
  charts/mattermost-enterprise-edition/values.yaml
Labels: AutoMerge
